ASPCrud/Models/Usuarios.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int idUsuario { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
    }
}

ASPCrud/Models/viewModels/UsuariosViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ASPCrud.Controllers;
namespace ASPCrud.Models.viewModels
{
    public class UsuariosViewModel
    {
        public int idUsuario { set; get; }

        [Required] 
        [Display(Name = "Usuario")]
        [UserTakenAttributes(ErrorMessage ="Usuario ya registrado")]
        public string usuario { set; get; }
        
        [Required]
        [Display(Name = "Contraseña")]               
        public string password { set; get; }
    }   

}

ASPCrud/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ASPCrud.Models;
using ASPCrud.Models.viewModels;

namespace ASPCrud.Controllers
{
    public class UsuariosController : Controller
    {
        // GET: Usuarios
        public ActionResult Index()
        {
            LoginViewModel model = new LoginViewModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Index(LoginViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (UsuariosEntities1 db = new UsuariosEntities1()) {

                        var us = db.Usuarios.Where(u => u.usuario == model.usuario && u.password == model.password).FirstOrDefault();
                        if(us != null) return Redirect("~/Usuarios/menu");
                    }
                }
                return View();
            }
            catch (Exception ex) {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult menu()
        {
            List<ListUsuariosViewModel> list;
            using (UsuariosEntities1 db = new UsuariosEntities1())
            {
                list = (from d in db.Usuarios
                        select new ListUsuariosViewModel
                        {
                            idUsuario = d.idUsuario,
                            usuario = d.usuario
                        }).ToList();
            }
            return View(list);
        }
       
        public ActionResult NuevoUsuario()
        {
            return View();
        }

        [HttpPost]
       public ActionResult NuevoUsuario(UsuariosViewModel u)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    
                    using (UsuariosEntities1 db = new UsuariosEntities1())
                    {
                        var user = new Usuarios();
                        user.usuario = u.usuario;
                        user.password = u.password;
                        db.Usuarios.Add(user);
                        db.SaveChanges();
                    }
                    return Redirect("~/Usuarios/menu");

                }
                return View(u);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            
        }

        public ActionResult Editar(int id)
        {
            EditUsuariosViewModel model = new EditUsuariosViewModel();
            using (UsuariosEntities1 db = new UsuariosEntities1())
            {
                var oUsuario = db.Usuarios.Find(id);
                model.usuario = oUsuario.usuario;
                model.idUsuario = oUsuario.idUsuario;
                System.Diagnostics.Debug.WriteLine(model.idUsuario + "usuario");
            }
           return View(model);
        }

        [HttpPost]

        public ActionResult Editar(EditUsuariosViewModel model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    System.Diagnostics.Debug.WriteLine(model.idUsuario + "usuario");
                    using (UsuariosEntities1 db = new UsuariosEntities1())
                    {
                        var user = db.Usuarios.Find(model.idUsuario);
                        if (user != null)
                        {
                            user.usuario = model.usuario;
                            db.SaveChanges();
                        }
                        else return View(model);
                    }
                    return Redirect("~/Usuarios/menu");

                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

        }

        public ActionResult Eliminar(int id)
        {
            UsuariosViewModel model = new UsuariosViewModel();
            using (UsuariosEntities1 db = new UsuariosEntities1())
            {
                var oUsuarios = db.Usuarios.Find(id);
                db.Usuarios.Remove(oUsuarios);
                db.SaveChanges();
            }
            return Redirect("~/Usuarios/menu");
        }
    }
}

ASPCrud/Views/Usuarios/Editar.cshtml
@model ASPCrud.Models.viewModels.EditUsuariosViewModel
@{
    ViewBag.Title = "Editar";
}

<h2>@ViewBag.Title</h2>



<div class="container">
    @using (Html.BeginForm("Editar", "Usuarios", FormMethod.Post))
    {
        <div class="row justify-content-center">
            <div class="col-8">
                <div>
                    @Html.HiddenFor(d=>d.idUsuario)
                </div>
                <div>
                    @Html.LabelFor(d => d.usuario)
                    @Html.TextBoxFor(d => d.usuario, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.usuario, null, new { @class = "alert" })
                </div>

            </div>
            <div style="margin:10px">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>
    }
</div>

ASPCrud/Views/Usuarios/Index.cshtml
@model ASPCrud.Models.viewModels.LoginViewModel

    
    <div class="container " style="width:30rem;height:80vh">
        <div class="row align-items-center" style="background-color:white; padding:2rem;border-color:black;border-width:1px;border-radius:5%">
            <div class="col-12 align-self-center">
                <h2>Iniciar Sesión</h2>

                @using (Html.BeginForm("Index", "Usuarios", FormMethod.Post))
                {
                    <div>
                        @Html.LabelFor(d => d.usuario)
                        @Html.TextBoxFor(d => d.usuario, "", new { @class = "form-control" })
                        @Html.ValidationMessageFor(d => d.usuario, null, new { @class = "alert" })
                    </div>
                    <div>
                        @Html.LabelFor(d => d.password)
                        @Html.PasswordFor(d => d.password, new { @class = "form-control" })

                    </div>
                    <div style="margin-top:10px" class="col-12">
                        <input type="submit" style="width:100%" class="btn btn-primary" value="Entrar" />
                    </div>
                }
            </div>

        </div>

    </div>

ASPCrud/Views/Usuarios/NuevoUsuario.cshtml
@model ASPCrud.Models.viewModels.UsuariosViewModel
@{
    ViewBag.Title = "NuevoUsuario";
}

<h2>@ViewBag.Title</h2>



<div class="container">
    @using (Html.BeginForm("NuevoUsuario", "Usuarios", FormMethod.Post))
    {
        <div class="row justify-content-center">
            <div class="col-8">
                <div>
                    @Html.LabelFor(d => d.usuario)
                    @Html.TextBoxFor(d => d.usuario, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.usuario, null, new { @class = "alert" })
                </div>
                <div>
                    @Html.LabelFor(d => d.password)
                    @Html.PasswordFor(d => d.password, new { @class = "form-control" })

                </div>
                
            </div>
            <div style="margin:10px">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>
    }
</div>

ASPCrud/Views/Usuarios/menu.cshtml
@model List<ASPCrud.Models.viewModels.ListUsuariosViewModel>
@{
    ViewBag.Title = "Usuarios";
}

<h2>@ViewBag.Title</h2>

<div class="container">


    <div class="row">
        <div class="col-12">
            <a style="width:100%" href="~/Usuarios/NuevoUsuario" class="btn btn-primary col-12">Nuevo Usuario</a>
        </div>

    </div>
    <div class="row" style="margin-top:1rem">
        <div class="col-md-12">

            <table class="table">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Usuario</th>
                    <th scope="col">Acciones</th>
                </tr>
                @foreach (var us in Model)
                {
                    <tr>
                        <td>@us.idUsuario</td>
                        <td>@us.usuario</td>
                        <td><a class="btn btn-success" href="~/Usuarios/Editar/@us.idUsuario">Editar</a></td>
                        <td><a class="btn btn-danger" href="~/Usuarios/Eliminar/@us.idUsuario">Eliminar</a></td>
                    </tr>
                }
            </table>
        </div>
    </div>

</div>